application: bandtasticnews
version: 5
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.3"

builtins:
- appstats: on

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /reports/.*
  script: reports.py
  login: admin
- url: /tasks/send_top_to_twitter
  script: crons.py
  login: admin
- url: /tasks/send_to_killmetrics
  script: crons.py
  login: admin
- url: /tasks/update_top_karma
  script: crons.py
  login: admin
- url: /tasks/cleanup_sessions
  script: crons.py
  login: admin
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico   
- url: /robots.txt             
  static_files: static/robots.txt 
  upload: static/robots.txt    
- url: /static
  static_dir: static
- url: /admin/.*
  script: admin.py
  login: admin
- url: .*
  script: main.py
